name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  github-token:  # id of input
    description: 'GITHUB_TOKEN variable used to authenticate with API'
    required: true
    default: 'NOT_SUPPLIED'
runs:
  using: 'node12'
  main: 'index.js'
