on: [push, pull_request]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - name: Hello world action step
      id: hello
      uses: junthehacker/pr-actions@v1.3
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        who-to-greet: 'Mona the Octocat'
